# Generated by Django 3.2.10 on 2022-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
