# Generated by Django 3.2.10 on 2022-01-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_cloth_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloth',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cloth_Name',
            new_name='Product_Name',
        ),
    ]
