# Generated by Django 3.2.10 on 2022-01-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220109_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
